/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.PdvController;
import javax.swing.JOptionPane;

/**
 *
 * @author anderson
 */
public class FormaPagamento extends javax.swing.JFrame {

    PdvController pdvController = new PdvController();
    double valorDescontro,valorTotal,novoValor,valorAcresmico,troco,valorTotalFixo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDescontoAcrescimo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescontoAcrescimo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelTotalAPagar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotalPago = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTroco = new javax.swing.JLabel();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jTextFieldValorPago = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBoxDescontoAcrescimo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxDescontoAcrescimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconto", "Acrescimo" }));
        getContentPane().add(jComboBoxDescontoAcrescimo);
        jComboBoxDescontoAcrescimo.setBounds(30, 40, 160, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Troco:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 190, 60, 22);

        jTextFieldDescontoAcrescimo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldDescontoAcrescimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDescontoAcrescimo.setText("0.00");
        jTextFieldDescontoAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescontoAcrescimoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldDescontoAcrescimo);
        jTextFieldDescontoAcrescimo.setBounds(210, 40, 110, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabelTotalAPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotalAPagar.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTotalAPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelTotalAPagar);
        jLabelTotalAPagar.setBounds(30, 10, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(390, 40, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total à pagar:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 10, 130, 22);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabelTotalPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotalPago.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTotalPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelTotalPago);
        jLabelTotalPago.setBounds(30, 10, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(390, 130, 190, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total pago:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 100, 110, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabelTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTroco.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabelTroco);
        jLabelTroco.setBounds(30, 10, 130, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(390, 220, 190, 50);

        jComboBoxFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão Debito", "Cartão Credito", " " }));
        getContentPane().add(jComboBoxFormaPagamento);
        jComboBoxFormaPagamento.setBounds(30, 130, 160, 40);

        jTextFieldValorPago.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldValorPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorPagoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldValorPago);
        jTextFieldValorPago.setBounds(210, 130, 110, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo Fenix 2 .png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-40, 190, 380, 283);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(470, 420, 100, 40);

        jButtonFinalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar);
        jButtonFinalizar.setBounds(360, 420, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_telaprincipal2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -10, 750, 490);

        setSize(new java.awt.Dimension(611, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public FormaPagamento() {
        initComponents();
        jTextFieldValorPago.requestFocus();
    }

    public void receberInformacoesPDV(String valorTotal){
        jLabelTotalAPagar.setText(valorTotal);
        valorTotalFixo = Double.parseDouble(valorTotal);        
    }
    
    private void jTextFieldDescontoAcrescimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescontoAcrescimoKeyPressed
        if(evt.getKeyCode() == 10){
            if(jLabelTotalPago.getText().isEmpty()){//verifica se ja foi preenchido o valor pago pelo cliente para poder fazer validacoes de pagamento
                if(jComboBoxDescontoAcrescimo.getSelectedItem().equals("Desconto")){
                    valorDescontro = Double.parseDouble(jTextFieldDescontoAcrescimo.getText());
                    valorTotal = Double.parseDouble(jLabelTotalAPagar.getText());
                    novoValor = valorTotal - valorDescontro;
                    jLabelTotalAPagar.setText(Double.toString(novoValor));
                }else{
                    valorAcresmico = Double.parseDouble(jTextFieldDescontoAcrescimo.getText());
                    valorTotal = Double.parseDouble(jLabelTotalAPagar.getText());
                    novoValor = valorTotal + valorAcresmico;
                    jLabelTotalAPagar.setText(Double.toString(novoValor));
                } 
                jTextFieldValorPago.requestFocus();
            }else{//se entrou aqui significa que foi informado o valor pago mas quiseram altrar o desconto ou acrescimo
                if(jComboBoxDescontoAcrescimo.getSelectedItem().equals("Desconto")){
                    valorDescontro = Double.parseDouble(jTextFieldDescontoAcrescimo.getText());
                    novoValor = valorTotalFixo - valorDescontro;
                    jLabelTotalAPagar.setText(Double.toString(novoValor));
                    //altera os labels com as novas informacoes apois o novo desconto
                    if(Double.parseDouble(jTextFieldValorPago.getText()) < Double.parseDouble(jLabelTotalAPagar.getText())){
                        JOptionPane.showMessageDialog(null, "Valor informado é inferior a venda. Cuidado com o desconto!");
                        jTextFieldValorPago.requestFocus();
                        jLabelTotalPago.setText("");
                        jLabelTroco.setText("");
                    }else{
                        jLabelTotalPago.setText(jTextFieldValorPago.getText());
                        troco = Double.parseDouble(jLabelTotalPago.getText()) - Double.parseDouble(jLabelTotalAPagar.getText());
                        jLabelTroco.setText(Double.toString(troco));
                    }                    
                }else{
                    valorAcresmico = Double.parseDouble(jTextFieldDescontoAcrescimo.getText());
                    novoValor = valorTotalFixo + valorAcresmico;
                    jLabelTotalAPagar.setText(Double.toString(novoValor));
                    //altera os labels com as novas informacoes apois o novo acrescimo
                    if(Double.parseDouble(jTextFieldValorPago.getText()) < Double.parseDouble(jLabelTotalAPagar.getText())){
                        JOptionPane.showMessageDialog(null, "Valor informado é inferior a venda. Cuidade com o acrescimo!");
                        jTextFieldValorPago.requestFocus();
                        jLabelTotalPago.setText("");
                        jLabelTroco.setText("");
                    }else{
                        jLabelTotalPago.setText(jTextFieldValorPago.getText());
                        troco = Double.parseDouble(jLabelTotalPago.getText()) + Double.parseDouble(jLabelTotalAPagar.getText());
                        jLabelTroco.setText(Double.toString(troco));
                    }
                } 
            }            
        }
    }//GEN-LAST:event_jTextFieldDescontoAcrescimoKeyPressed

    private void jTextFieldValorPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorPagoKeyPressed
        if(evt.getKeyCode() == 10){
            if(Double.parseDouble(jTextFieldValorPago.getText()) < Double.parseDouble(jLabelTotalAPagar.getText())){
                JOptionPane.showMessageDialog(null, "Valor informado é inferior a venda");
                jTextFieldValorPago.requestFocus();
                jLabelTotalPago.setText("");
                jLabelTroco.setText("");
            }else{
                jLabelTotalPago.setText(jTextFieldValorPago.getText());
                troco = Double.parseDouble(jLabelTotalPago.getText()) - Double.parseDouble(jLabelTotalAPagar.getText());
                jLabelTroco.setText(Double.toString(troco));
            }
        }
    }//GEN-LAST:event_jTextFieldValorPagoKeyPressed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldDescontoAcrescimo.setText("0.00");
        jTextFieldValorPago.setText("");
        jLabelTotalAPagar.setText("");
        jLabelTotalPago.setText("");
        jLabelTroco.setText("");
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        if(Double.parseDouble(jLabelTotalAPagar.getText()) <= Double.parseDouble(jTextFieldValorPago.getText())){
            PdvController.receberConfirmacaoPagamento();
        }else{
            JOptionPane.showMessageDialog(null, "Informe o valor para pagamento corretamente!");
            jTextFieldValorPago.requestFocus();
        }
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JComboBox<String> jComboBoxDescontoAcrescimo;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotalAPagar;
    private javax.swing.JLabel jLabelTotalPago;
    private javax.swing.JLabel jLabelTroco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldDescontoAcrescimo;
    private javax.swing.JTextField jTextFieldValorPago;
    // End of variables declaration//GEN-END:variables
}
