/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelDao.GerarRelatorioPDF;
import Negocio.Exceptions.CnpjInvalidoException;
import Negocio.Exceptions.CpfInvalidoException;
import Negocio.Exceptions.PessoaNaoExisteException;
import Negocio.Exceptions.ValidacaoException;
import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author anderson
 */
public class Relatorio extends javax.swing.JFrame {

    private GerarRelatorioPDF gerarRelatorioPDF ;
    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        gerarRelatorioPDF = new GerarRelatorioPDF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCpfCnpj = new javax.swing.JTextField();
        jButtonGerarSomatorio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Somatório de venda por cliente"));
        jPanel1.setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "CNPJ" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(178, 44, 95, 34);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CPF / CNPJ:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 96, 22);
        jPanel1.add(jTextFieldCpfCnpj);
        jTextFieldCpfCnpj.setBounds(10, 44, 137, 34);

        jButtonGerarSomatorio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonGerarSomatorio.setText("Gerar");
        jButtonGerarSomatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarSomatorioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGerarSomatorio);
        jButtonGerarSomatorio.setBounds(100, 90, 75, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 290, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque atual"));
        jPanel3.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Gerar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(100, 40, 75, 31);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 160, 290, 110);

        setSize(new java.awt.Dimension(329, 318));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarSomatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarSomatorioActionPerformed
        try {
            if(jComboBox1.getSelectedItem().equals("CPF")){
               gerarRelatorioPDF.criarRelatorioSomatorio(jTextFieldCpfCnpj.getText(), 0);
            }else{
                gerarRelatorioPDF.criarRelatorioSomatorio(jTextFieldCpfCnpj.getText(), 1);
            }
            JOptionPane.showMessageDialog(null, "Relatorio Gerado em: \nC:\\ Registros Fenix Sistemas \\ relatorios");
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ValidacaoException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButtonGerarSomatorioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            gerarRelatorioPDF.criarRelatorioEstoque();
            JOptionPane.showMessageDialog(null, "Relatorio Gerado em: \nC:\\ Registros Fenix Sistemas \\ relatorios");
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGerarSomatorio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCpfCnpj;
    // End of variables declaration//GEN-END:variables
}
